services:
  rabbitmq:
    container_name: rebmitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: always

  # postgres:
  #   container_name: postgres
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_DB=podcast_database
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=Akl79333
  #   networks:
  #     - main
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  celery_worker:
    container_name: celery_worker
    command: celery -A config worker -l INFO
    depends_on:
      - app
      - rabbitmq
      # - postgres
    build: .
    environment: 
      - C_FORCE_ROOT="true"
    networks:
      - main
    restart: always
  
  app:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    depends_on:
      # - postgres
      - rabbitmq
    expose:
      - "8000"
    networks:
      - main
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - main
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
  

networks:
  main:

volumes:
  postgres_data:
  redis_data: