# Generated by Django 4.2.5 on 2023-10-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
