# Generated by Django 4.2.5 on 2023-10-16 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='xml_link',
        ),
    ]
