# Generated by Django 4.2.5 on 2023-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_channel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='xml_link',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
    ]
