# Generated by Django 4.2.5 on 2023-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_channel_xml_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='xml_link',
            field=models.URLField(),
        ),
    ]
