# Generated by Django 4.2.5 on 2023-10-28 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notificationinfo_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationinfo',
            old_name='massage',
            new_name='message',
        ),
    ]
